### ISSUE TITLE
IR probe 1.4 don't working

### ISSUE THREAD

**Issue by nemocaledonie** [Aus3D/z-probe#2]
Hello, I purchased a small probe Aus3D IR 1.4 for my 3D printer.
Having never had time to climb it, this morning I decided to ride it.

Unfortunately the probe that I bought does not work (no small light to the ignition).
I tried different power supplies (that of the MKS BASE card, then that of a WEMOS D1), and the 5v is present.
After looking at the magnifying glass on the map I saw that two small legs of the IC were welded together, so I took my soldering iron and removed this invasive weld.
Now I tell myself that if the IC is programmed as an Arduino, and although with this solder it could never be programmed.
Is that the right question? or simply my little card is roasted? (which would be a shame because I have never used it and at nearly 30 € ... it is dear waste) or else can we reprogram it? if so how and where can I find the firmware?

**Comment by chrissbarr** [comment]
Hi @nemocaledonie,

Sorry to hear that your IR probe isn't working!

It is possible that the solder short you found on the IC is responsible. None of the legs are supposed to be shorted together, though there are a few unused pins that could be shorted without causing a problem. If you let me know which pins (maybe in a photo?) were shorted, I'd be happy to check if they could have interfered with programming as you suspect.

That said, we do test each board when we program them, and confirm both that the firmware is running and that they're triggering reliably. Because of this, I think it's unlikely the short interfered with programming, as that is something we would have noticed. 

Whatever the cause, it does sound like there's a problem. If you can email us at support@aus3d.com.au with your order number, and reference your post here, I'll make sure we get a replacement probe sent out to you.
